### ISSUE TITLE
How to configure local BED/BAM file as data source?

### ISSUE THREAD

**Issue by waynewang6660** [WTSI-decipher-grp/Genoverse#81]
How to configure local BED/BAM file as data source?Is there a case?

**Comment by pdl** [comment]
The model's dataFile attribute is passed to [FileReader.readAsText()](https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsText). How you get the file there is up to the developer using Genoverse.

NB: You can normally drag and drop a file onto Genoverse and it will attempt to parse and render it as a track.

**Comment by waynewang6660** [comment]
Thank you very much,it works perfect!
